name: Production - Main Plan

on:
  push:
    branches:
      - main
    paths:
      - "environments/production/**"
      - "modules/**"
      - ".github/workflows/production-main-plan.yml"

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Main Plan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.5

      - name: Terraform Verify
        run: terraform version

      - name: Terraform Format Check
        working-directory: .
        run: terraform fmt -check -diff -recursive

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::315435444725:role/GitHubActions-Terraform-Production-Role
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: environments/production
        run: terraform init

      - name: Terraform Validate
        working-directory: environments/production
        run: terraform validate

      - name: Terraform Plan
        working-directory: environments/production
        run: terraform plan -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: production-tfplan
          path: environments/production/tfplan
          retention-days: 1