name: Production - Main Destroy

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform-destroy:
    name: Terraform Production Destroy
    runs-on: ubuntu-latest

    concurrency:
      group: production-terraform
      cancel-in-progress: false

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.15.5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.2.3
        with:
          role-to-assume: arn:aws:iam::315435444725:role/GitHubActions-Terraform-Production-Destroy-Role
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity

      - name: Terraform Init
        working-directory: environments/production
        run: terraform init

      - name: Terraform Destroy
        working-directory: environments/production
        run: terraform destroy -auto-approve